---
chdir: /home/interpreters/project
environment: production
timeout: 30
log: /home/interpreters/project/log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 1
socket: tmp/sockets/thin.socket
daemonize: true
