import path from "path";
import HtmlWebpackPlugin from 'html-webpack-plugin';
import { CleanWebpackPlugin } from 'clean-webpack-plugin';
import CopyPlugin from 'copy-webpack-plugin';

export default {
  stats: {
    children: false
  },

  resolve: { 
    extensions: [".jsx", ".js"],
    alias: {
      vendor: path.resolve(__dirname, '../../vendor')
    }
  },

  entry: {
    [`app.en`]: 
      ["core-js/stable", "regenerator-runtime/runtime", "whatwg-fetch", `./webpack_entries/spa/autogenerated/entry.en.js`]
  },

  output: {
    publicPath: "/",
    path: path.resolve(__dirname, "../../dist"),
  },

  devServer: {
    contentBase: path.resolve(__dirname, "../../dist"),
    historyApiFallback: true,
    openPage: "translation"
  },

  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      template: 'lib/index.html'
    }),

    new CopyPlugin([
      { from: './vendor/images/favicon.png', to: "./" },
      { from: './vendor/images/favicon.ico', to: "./" },
    ]),
  ],

  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /@babel(?:\/|\\{1,2})runtime|core-js/,
        use: [ 
          "babel-loader",
          'webpack-import-glob-loader'
        ]
      },
      {
        test: /\.s[ac]ss$/i,
        use: [
          "style-loader",
          "css-loader",
          {
            loader: 'sass-loader',
            options: {
              implementation: require('sass'),
              sassOptions: {
                includePaths: ['lib', 'node_modules']
              },
            },
          }
        ],
      },
      {
        test: /\.(png|jpe?g|gif)$/i,
        use: [
          'file-loader'
        ],
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf|svg)$/,
        use: [
          'file-loader'
        ],
      },
    ]
  },
};